{
	"schema_version": 1,
	"slug": "active",
	"mode": "{{ mode }}",
	"colors": {
		"accent": "{{ accent }}",
		"selection": "{{ selection }}",
		"muted": "{{ muted }}",
		"background": "{{ background }}",
		"dark_background": "{{ dark_background }}",
		"darker_background": "{{ darker_background }}",
		"lighter_background": "{{ lighter_background }}",
		"foreground": "{{ foreground }}",
		"dark_foreground": "{{ dark_foreground }}",
		"light_foreground": "{{ light_foreground }}",
		"bright_foreground": "{{ bright_foreground }}",
		"red": "{{ red }}",
		"yellow": "{{ yellow }}",
		"green": "{{ green }}",
		"cyan": "{{ cyan }}",
		"blue": "{{ blue }}",
		"magenta": "{{ magenta }}",
		"bright_red": "{{ bright_red }}",
		"bright_yellow": "{{ bright_yellow }}",
		"bright_green": "{{ bright_green }}",
		"bright_cyan": "{{ bright_cyan }}",
		"bright_blue": "{{ bright_blue }}",
		"bright_magenta": "{{ bright_magenta }}"
	}
}
