$font = Terminess Nerd Font Propo
$foreground = rgb(d3c6aa)
$yellow = rgba(219, 188, 127, 0.85)
$green = rgba(167, 192, 128, 0.85)
$red = rgba(230, 126, 128, 0.85)
$grey = rgb(859289)
$transparent = rgba(0, 0, 0, 0.00)

general {
    hide_cursor = true
}

background {
    monitor =
    path = screenshot
    blur_passes = 4
    color = rgb(272e33)
}

label {
    monitor =
    text = $TIME
    color = $foreground
    font_size = 240
    font_family = $font
    position = 0, 206
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B"
    color = $grey
    font_size = 70
    font_family = $font
    position = 0, 41
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 1040, 160
    outline_thickness = 4
    rounding = 0
    dots_center = true
    dots_size = 0.5
    dots_spacing = 0.25
    inner_color = $transparent
    outer_color = $yellow
    check_color = $green
    fail_color = $red
    font_color = $foreground
    font_family = $font
    fade_on_empty = false
    placeholder_text = password
    fail_text = $PAMFAIL
    position = 0, -160
    halign = center
    valign = center
}
