# https://wiki.hypr.land/Configuring/

# Source subconfigs
source = ~/.config/hypr/configs/monitors.conf
source = ~/.config/hypr/configs/programs.conf
source = ~/.config/hypr/configs/autostart.conf
source = ~/.config/hypr/configs/environment.conf
source = ~/.config/hypr/configs/permissions.conf
source = ~/.config/hypr/configs/look-and-feel.conf
source = ~/.config/hypr/configs/input.conf
source = ~/.config/hypr/configs/keybindings.conf
source = ~/.config/hypr/configs/windows.conf

