set -g base-index 1
set -g pane-base-index 1
set -g status-left " session:[#S] "
set -g status-left-length 20
set -g status-position top
set -g status-style "bg=#2E383C,fg=#D3C6AA"
set -g status-left-style "bg=#272E33,fg=#A7C080"
set -g status-right-style "bg=#272E33,fg=#D3C6AA"
set -g status-right ""
set -g window-status-style "bg=#272E33,fg=#859289"
set -g window-status-current-style "bg=#2E383C,fg=#D3C6AA"
set -g window-status-format " #I:#W "
set -g window-status-current-format " #I:#W "
set -g message-style "bg=#2E383C,fg=#D3C6AA"

bind r source-file ~/.tmux.conf \; display-message "tmux config reloaded"
