name = "a1exk"

ascii_1 = """
██████╗ ██╗     ███████╗██╗  ██╗    
██╔══██╗██║     ██╔════╝╚██╗██╔╝    
███████║██║     █████╗   ╚███╔╝     
██╔══██║██║     ██╔══╝   ██╔██╗     
██║  ██║███████╗███████╗██╔╝ ██╗    
╚═╝  ╚═╝╚══════╝╚══════╝╚═╝  ╚═╝   
                               
   Hyprland + Everforest      
"""
